//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<Compositor> Compositors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<RecordCompany> RecordCompanies { get; set; }
        public virtual DbSet<UserA> UserAs { get; set; }
    }
}
