//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CompositionID { get; set; }
    
        public virtual Composition Composition { get; set; }
    }
}
